name: ci_validation 

on:
  push:
    branches:
    - main
    paths:
      - 'notebooks/**.ipynb'
      #- 'notebooks/**'

env: 
  WEBBPSF_PATH: $HOME/data/webbpsf-data

jobs:
  gather-notebooks:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Gather changed notebooks
      id: changed-files
      uses: tj-actions/changed-files@v18.4
      with:
        files: |
          **/*.ipynb
        
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.12
      uses: actions/setup-python@v2 ## needed for caching
      with:
          python-version: 3.8.12
          cache: 'pip'
    - name: Add conda to system path
      run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
          #conda env update --file CIenvironment.yml --name base
          pip install -r requirements.txt
          pip install pytest
          pip install nbval
          pip install nbconvert
    - name: Execute notebooks
      run: |
          jupyter nbconvert --template classic --to html --execute ${{ steps.changed-files.outputs.modified_files }}
