name: ci_validation 

on:
  push:
    branches:
    - main
    paths:
     # - 'notebooks/**.ipynb'
      - 'notebooks/**'

env: 
  WEBBPSF_PATH: $HOME/data/webbpsf-data

jobs:
  gather-notebooks:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Run changed-files with defaults
        id: changed-files
        uses: tj-actions/changed-files@v22.2
      - name: CheckForChanges
        run: for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file" was changed !!!!!!!!
        
     # - id: set-matrix
      #  run: echo "::set-output name=matrix::$(find notebooks -name "*.ipynb" | jq -cnR '[inputs | select(length>0)]')"

  notebook-execution:
    needs: gather-notebooks
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            notebooks: ${{ fromJson(needs.gather-notebooks.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2   
      #- run: | 
      #      pip install -r ${${{ matrix.notebooks }}%/*}/requirements.txt
      - uses: actions/checkout@v2
      - name: Set up Python 3.8.12
        uses: actions/setup-python@v2 ## needed for caching
        with:
          python-version: 3.8.12
          cache: 'pip'
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          #conda env update --file CIenvironment.yml --name base
          pip install -r requirements.txt
          pip install pytest
          pip install nbval
          pip install nbconvert
      - name: Execute notebooks
        run: |
          jupyter nbconvert --to ipynb --execute "${{ matrix.notebooks }}"
      #- name: Validate notebooks 
      #  run: |
      #   pytest --nbval "${{ matrix.notebooks }}"
